#59: !join can allow players to join case-sensitive teams
alopezlago/QuizBowlDiscordScoreTracker pull request #66
Opened 2020-11-24 03:13 UTC by Sam-per

- Forces all case variations of team names to return to the original spelling

When calling !score when teammates would fail to use the same casing in their team name, it would result in situations where the call would succeed (as the dictionary was case-insensitive), but the player's team name would use the player's casing. This would result in the scoreboard having players on team Alpha and team ALPHA listed separately.

One peculiarity of the current solution is that the success message still uses the user's casing of their team name, even though they will be added to the correct casing team. In the example from the test cases, the player succeeds in joining team Alpha using command !join ALPHA with a response message "@mention is on ALPHA"

Resolves #59

2020-11-26 22:08 UTC, alopezlago commented
There's a couple way to fix the peculiarity:
1. Make TryAddPlayerToTeam return the proper team name in an out parameter
2. In GeneralCommandHandler.JoinTeamAsync, call teamManager.GetTeamIdOrNull with the player's ID, then use teamManager.GetTeamIdToName to get the proper team name. 
    - You don't technically need to do the second part with how it's implemented now, but we'd be  relying on the behavior of a specific implementation of ISelfManagedTeamManager where teamId is the same as teamName, which isn't something we guarantee.

Let me know if you want to address the peculiarity.

2020-11-27 03:48 UTC, Sam-per commented
I ended up going with the second option you listed (GetTeamIdOrNull into GetTeamIdToBame).

Needless to say, it was a lot easier to update than changing the method signature of TryAddPlayerToTeam

2020-11-27 04:43 UTC, alopezlago requested changes
Just use await/async in JoinTeamAsync instead of using .Result, which makes them synchronous.

2020-11-27 04:43 UTC, alopezlago commented on QuizBowlDiscordScoreTracker/Commands/GeneralCommandHandler.cs
> +            string teamId = game.TeamManager.GetTeamIdOrNull(this.Context.User.Id).Result;
Convert this method to async, then await on these two methods. Better to use async/await than make this synchronous.

2020-11-27 18:43 UTC, alopezlago approved these changes

2020-11-27 18:43 UTC, merged